spring:
  application:
    name: eureka

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
  server:
    enable-self-preservation: false